version: 1
builder:
  configs:
    - platform: ios
      documentation_targets:
      - EpoxyCore
      - EpoxyCollectionView
      - EpoxyBars
      - EpoxyNavigationController
      - EpoxyPresentations
      - EpoxyLayoutGroups
